services:
  k3s-server:
    image: rancher/k3s
    container_name: k3s-server
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - K3S_TOKEN=supersecrettoken
      - K3S_NODE_NAME=k3s-server
    volumes:
      - k3s-server-data:/var/lib/rancher/k3s
      - ./output:/output
    ports:
      - 6443:6443
      - 80:80
      - 443:443
    command: server
    networks:
      - k3s-net

  k3s-node:
    image: rancher/k3s
    privileged: true
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=supersecrettoken
    volumes:
      - /var/lib/rancher/k3s
    networks:
      - k3s-net
    depends_on:
      - k3s-server

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_USER=co2_operator
      - POSTGRES_PASSWORD=co2_operator
      - POSTGRES_DB=co2_operator
    ports:
      - 5432:5432

volumes:
  k3s-server-data:

networks:
  k3s-net:
    driver: bridge
